services:
    sonata.admin.manager.influxdb:
        class: Javer\InfluxDB\AdminBundle\Model\ModelManager
        arguments:
            - '@javer_influxdb.odm.measurement_manager'
            - '@property_accessor'
        tags: ['sonata.admin.manager']

    sonata.admin.builder.influxdb_form:
        class: Javer\InfluxDB\AdminBundle\Builder\FormContractor
        arguments:
            - '@form.factory'
            - '@form.registry'

    sonata.admin.builder.influxdb_list:
        class: Javer\InfluxDB\AdminBundle\Builder\ListBuilder
        arguments:
            - '@sonata.admin.guesser.influxdb_list_chain'
            - []

    sonata.admin.guesser.influxdb_list:
        class: Javer\InfluxDB\AdminBundle\FieldDescription\TypeGuesser
        tags: ['sonata.admin.guesser.influxdb_list']

    sonata.admin.guesser.influxdb_list_chain:
        class: Sonata\AdminBundle\FieldDescription\TypeGuesserChain
        arguments:
            - ['@sonata.admin.guesser.influxdb_list']

    sonata.admin.builder.influxdb_show:
        class: Javer\InfluxDB\AdminBundle\Builder\ShowBuilder
        arguments:
            - '@sonata.admin.guesser.influxdb_show_chain'
            - []

    sonata.admin.guesser.influxdb_show:
        class: Javer\InfluxDB\AdminBundle\FieldDescription\TypeGuesser
        tags: ['sonata.admin.guesser.influxdb_show']

    sonata.admin.guesser.influxdb_show_chain:
        class: Sonata\AdminBundle\FieldDescription\TypeGuesserChain
        arguments:
            - ['@sonata.admin.guesser.influxdb_show']

    sonata.admin.builder.influxdb_datagrid:
        class: Javer\InfluxDB\AdminBundle\Builder\DatagridBuilder
        arguments:
            - '@form.factory'
            - '@sonata.admin.builder.filter.factory'
            - '@sonata.admin.guesser.influxdb_datagrid_chain'
            - '%form.type_extension.csrf.enabled%'

    sonata.admin.guesser.influxdb_datagrid:
        class: Javer\InfluxDB\AdminBundle\FieldDescription\FilterTypeGuesser
        tags: ['sonata.admin.guesser.influxdb_datagrid']

    sonata.admin.guesser.influxdb_datagrid_chain:
        class: Sonata\AdminBundle\FieldDescription\TypeGuesserChain
        arguments:
            - ['@sonata.admin.guesser.influxdb_datagrid']

    sonata.admin.influxdb.filter.type.boolean:
        class: Javer\InfluxDB\AdminBundle\Filter\BooleanFilter
        tags:
            - { name: sonata.admin.filter.type, alias: influxdb_boolean }

    sonata.admin.influxdb.filter.type.callback:
        class: Javer\InfluxDB\AdminBundle\Filter\CallbackFilter
        tags:
            - { name: sonata.admin.filter.type, alias: influxdb_callback }

    sonata.admin.influxdb.filter.type.choice:
        class: Javer\InfluxDB\AdminBundle\Filter\ChoiceFilter
        tags:
            - { name: sonata.admin.filter.type, alias: influxdb_choice }

    sonata.admin.influxdb.filter.type.date:
        class: Javer\InfluxDB\AdminBundle\Filter\DateFilter
        tags:
            - { name: sonata.admin.filter.type, alias: influxdb_date }

    sonata.admin.influxdb.filter.type.date_range:
        class: Javer\InfluxDB\AdminBundle\Filter\DateRangeFilter
        tags:
            - { name: sonata.admin.filter.type, alias: influxdb_date_range }

    sonata.admin.influxdb.filter.type.datetime:
        class: Javer\InfluxDB\AdminBundle\Filter\DateTimeFilter
        tags:
            - { name: sonata.admin.filter.type, alias: influxdb_datetime }

    sonata.admin.influxdb.filter.type.datetime_range:
        class: Javer\InfluxDB\AdminBundle\Filter\DateTimeRangeFilter
        tags:
            - { name: sonata.admin.filter.type, alias: influxdb_datetime_range }

    sonata.admin.influxdb.filter.type.number:
        class: Javer\InfluxDB\AdminBundle\Filter\NumberFilter
        tags:
            - { name: sonata.admin.filter.type, alias: influxdb_number }

    sonata.admin.influxdb.filter.type.string:
        class: Javer\InfluxDB\AdminBundle\Filter\StringFilter
        tags:
            - { name: sonata.admin.filter.type, alias: influxdb_string }

    sonata.admin.data_source.influxdb:
        class: Javer\InfluxDB\AdminBundle\Exporter\DataSource

    sonata.admin.field_description_factory.influxdb:
        class: Javer\InfluxDB\AdminBundle\FieldDescription\FieldDescriptionFactory
        arguments:
            - '@javer_influxdb.odm.measurement_manager'
