name: Test

on:
    push:
    pull_request:
        types: [opened, synchronize, edited, reopened]

jobs:
    test:
        name: PHP ${{ matrix.php-version }} + Symfony ${{ matrix.symfony-version }} + Sonata ${{ matrix.sonata-version }}

        runs-on: ubuntu-18.04

        continue-on-error: ${{ matrix.experimental }}

        strategy:
            matrix:
                include:
                    - php-version: '7.4'
                      symfony-version: '4.4.*'
                      sonata-version: 'dev-master'
                      experimental: false
                    - php-version: '7.4'
                      symfony-version: '5.2.*'
                      sonata-version: 'dev-master'
                      experimental: false
                    - php-version: '8.0'
                      symfony-version: '4.4.*'
                      sonata-version: 'dev-master'
                      experimental: false
                    - php-version: '8.0'
                      symfony-version: '5.2.*'
                      sonata-version: 'dev-master'
                      experimental: false

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  coverage: none
                  ini-values: "memory_limit=-1"
                  php-version: ${{ matrix.php-version }}
                  tools: composer:v2, cs2pr

            - name: Validate composer.json
              run: composer validate --no-check-lock

            - name: Configure Symfony version
              run: composer require --no-update symfony/symfony "${{ matrix.symfony-version }}"

            - name: Configure SonataAdminBundle version
              run: composer require --no-update sonata-project/admin-bundle "${{ matrix.sonata-version }}"

            - name: Install Composer dependencies
              uses: "ramsey/composer-install@v1"
              with:
                  composer-options: "--prefer-dist"

            - name: Setup problem matchers for PHP
              run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

            - name: Lint PHP files
              run: find Admin Builder Datagrid DependencyInjection Exporter Filter Guesser Model -name "*.php" -print0 | xargs -0 -n1 -P8 php -l

            - name: Validate code style
              run: vendor/bin/phpcs -q --report=checkstyle | cs2pr
